### ISSUE TITLE
Serve with ExpressJS

### ISSUE THREAD

**Issue by rafcontreras** [ovhemert/gatsby-plugin-brotli#3]
Hi there,

I promise I did a Google search before asking this. If I wanted to use Express to serve my site, is there a setting to serve the Brotli files as a priority, or would it just work?

**Comment by ovhemert** [comment]
If you have a website generated with Gatsby, and want to serve it with Express, you would normally place the contents in the [static-folder](https://expressjs.com/en/starter/static-files.html). Express will just serve the files that are available.

But if you want to make sure that the Brotli compressed files are served before the GZIP-ed or decompressed versions, you should use some middleware that takes care of it, because it's not baked into Express by default.

Try [express-static-gzip](https://www.npmjs.com/package/express-static-gzip), it also supports the Brotli compressed versions of files. I think that would be the this you're looking for.
