### ISSUE TITLE
gzip fallback?

### ISSUE THREAD

**Issue by DylanTackoor** [ovhemert/gatsby-plugin-brotli#5]
Any chance it would be possible to have a gzip fallback, possibly with gatsby-plugin-zopfli?

**Comment by ovhemert** [comment]
This would be something that your server should handle.

If you generate both .br and .gz files with my 2 plugins, they will both exist in your web folder. But the decision which files to serve to the client depends on the server.
Your webserver should inspect the headers and based on what the client supports send the correct file. This could start with Brotli (file.js.br) and use Zopfli (file.js.gz) as fallback when client does not support Brotli.

When the client supports GZip, it also supports Zopfli, because they are compatiple. So, no need to fallback from Zopfli to GZip. 

The plugins just _prepare_ the files that _could_ be served.

**Comment by DylanTackoor** [comment]
Awesome, I'll move forward with using both compression plugins. Thanks for the help!

**Comment by ovhemert** [comment]
Good luck 😉
